name: publish-crate


on:
  release:
    types: [published, created]

jobs:
  publish-crate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Publish to crates.io
        run: cargo publish --token ${CARGO_PUBLISH}
        env:
          CARGO_PUBLISH: ${{ secrets.CARGO_PUBLISH }}


