name: publish-release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: lts

      - name: Run Script
        run: deno task publish-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

